### ISSUE TITLE
Header and Footer Question

### ISSUE THREAD

**Issue by johnnydevs** [panique/php-login#557]
Firstly thank you to everyone for all the hard work, I am gradually building upon this framework in order to build a library app. I am quite new to php and this is a great way for me to further my personal development. I am able to create new pages, load models, and render views etc, however I am a bit unclear about the header and footer - these aren't views are they? They don't behave like the rest of the files as regards loading/calling functions.

I'll give an example, I have a table called favourite which contains basic user and book details. I have a query which counts the number of rows in this table and displays it on the views/login/showprofile.php page as a small notification "You have this number of favourites"  (in the header section I created a new div on the right hand side).

In order to do this I created a function favouriteTotal() in my login model - see below

    public function favouriteTotal()
    {
        ... query ...

        $fav = array();
        foreach ($query->fetchAll() as $favs) {   
            $fav[$favs->id] = new stdClass();
            $fav[$favs->id]->book_id = $favs->book_id;
        }
        return $fav;
    }

I then created a function in my login controller - see below

    function showProfile()
    {
        Auth::handleLogin();
        $login_model = $this->loadModel('Login');
        $this->view->Favcount = $login_model->favouriteTotal();
        $this->view->render('login/showprofile');
    }

In the application/views/_templates/header.php I added the following code

    "You have this number of favourites" <?php echo count($this->Favcount); ?>

This works perfectly, but only on the showprofile.php page. When I move to any other page I receive an error Notice:  Undefined property: View::$Favcount in C..\application\views\_templates\header.php on line 151.

Am I missing something or doing something very silly? I appreciate any help. Still learning!

Regards,
Johnny

**Comment by panique** [comment]
He @johnnydevs , please note that this is just a bug / feature list for development, not a support thing. Personal support is not really possible, you know, no time for this and so :)

Anyway, regarding your question:  You are getting the `$this->view->Favcount` property only in the showprofile controller, so it's logically only available in yourproject.com/login/showprofile. To be honest I don't get the problem here. If you want some kind of information in ALL views, then you'll have to get this for all controller-actions for sure.

In a well-constructed application you would do this probably in another way, like getting this data already in the constructor or handling it via $_SESSION or something similar.

**Comment by johnnydevs** [comment]
Thank you for that. I appreciate you taking the time to comment. That information helps, and yes I do want the data to be available in ALL views as it is a header notification area. I suppose I can do this manually for each view as the amount of pages I have is manageable. Thanks again @panique
